version 2
orbs:
    hello: circleci/hello-build@0.0.8
commands:
    sayhello:
        description: "Command name is SayHello"
        parameters:
            to:
                type: String
                default: "Hello Word"
        steps: 
            - run: echo <<parametrs.to>>
